#!/usr/bin/env python3
"""Fail closed when release dependency inputs or lockfiles drift."""

from __future__ import annotations

import json
import re
import sys
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SHA_REF = re.compile(r"^[0-9a-f]{40}$")
REQUIREMENT = re.compile(r"^([A-Za-z0-9_.-]+)(\[[^]]+\])?(.*)$")


def _fail(message: str) -> None:
    raise ValueError(message)


def _canonical_requirement(value: str) -> str:
    match = REQUIREMENT.match(value.strip())
    if not match:
        _fail(f"invalid requirement: {value!r}")
    name, extras, suffix = match.groups()
    name = name.lower().replace("_", "-").replace(".", "-")
    normalized_suffix = re.sub(r"\s+", "", suffix)
    return f"{name}{(extras or '').lower()}{normalized_suffix}"


def _input_requirements(path: Path) -> set[str]:
    values: set[str] = set()
    for raw in path.read_text("utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or line.startswith(("-r ", "-c ")):
            continue
        values.add(_canonical_requirement(line))
    return values


def _verify_lock(path: Path) -> None:
    text = path.read_text("utf-8")
    if "autogenerated by uv" not in text:
        _fail(f"{path.name} is not an identified generated lockfile")

    blocks: list[list[str]] = []
    current: list[str] = []
    for line in text.splitlines():
        is_entry = bool(line and not line[0].isspace() and not line.startswith("#") and "==" in line)
        if is_entry:
            if current:
                blocks.append(current)
            current = [line]
        elif current:
            current.append(line)
    if current:
        blocks.append(current)
    if not blocks:
        _fail(f"{path.name} contains no pinned packages")

    for block in blocks:
        first = block[0].rstrip(" \\")
        requirement_part = first.split(";", 1)[0].strip()
        if "==" not in requirement_part or any(
            op in requirement_part for op in (">=", "<=", "~=", "!=")
        ):
            _fail(f"{path.name} contains a non-exact pin: {first}")
        if not any("--hash=sha256:" in line for line in block):
            _fail(f"{path.name} contains an unhashed pin: {first}")


def _verify_python_inputs() -> None:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text("utf-8"))
    declared = {_canonical_requirement(item) for item in project["project"]["dependencies"]}
    lock_inputs = _input_requirements(ROOT / "requirements.in")
    lock_inputs.discard("hatchling==1.31.0")
    if declared != lock_inputs:
        missing = sorted(declared - lock_inputs)
        extra = sorted(lock_inputs - declared)
        _fail(f"requirements.in drift (missing={missing}, extra={extra})")

    for name in ("requirements.lock", "requirements-dev.lock"):
        _verify_lock(ROOT / name)

    dev_input = (ROOT / "requirements-dev.in").read_text("utf-8")
    if "-r requirements.in" not in dev_input or "-c requirements.lock" not in dev_input:
        _fail("requirements-dev.in must reuse and constrain the runtime dependency graph")


def _verify_node_lock() -> None:
    package = json.loads((ROOT / "desktop" / "package.json").read_text("utf-8"))
    lock = json.loads((ROOT / "desktop" / "package-lock.json").read_text("utf-8"))
    if lock.get("lockfileVersion") != 3:
        _fail("desktop/package-lock.json must use lockfileVersion 3")
    root_package = lock.get("packages", {}).get("")
    if not root_package:
        _fail("desktop/package-lock.json has no root package")
    for field in ("dependencies", "devDependencies"):
        if package.get(field, {}) != root_package.get(field, {}):
            _fail(f"desktop/package-lock.json {field} drifted from package.json")


def _verify_release_commands() -> None:
    surfaces = [
        ROOT / "Dockerfile",
        ROOT / "Makefile",
        ROOT / "build-desktop.sh",
        *sorted((ROOT / ".github" / "workflows").glob("*.yml")),
    ]
    for path in surfaces:
        text = path.read_text("utf-8")
        if re.search(r"\bnpm\s+install(?:\s|$)", text):
            _fail(f"{path.relative_to(ROOT)} uses npm install instead of npm ci")
        for line_number, line in enumerate(text.splitlines(), 1):
            if re.search(r"\bpip\s+install\b", line) and re.search(
                r"-r\s+requirements(?:-dev)?\.lock", line
            ):
                if "--require-hashes" not in line:
                    _fail(
                        f"{path.relative_to(ROOT)}:{line_number} installs a lock without hashes"
                    )

    action_files = [ROOT / "action.yml", *sorted((ROOT / ".github").rglob("*.yml"))]
    for path in action_files:
        for line_number, line in enumerate(path.read_text("utf-8").splitlines(), 1):
            match = re.search(r"\buses:\s*([^\s#]+)", line)
            if not match:
                continue
            action = match.group(1)
            if action.startswith("./"):
                continue
            ref = action.rsplit("@", 1)[-1]
            if not SHA_REF.fullmatch(ref):
                _fail(f"{path.relative_to(ROOT)}:{line_number} action is not SHA pinned: {action}")


def main() -> int:
    try:
        _verify_python_inputs()
        _verify_node_lock()
        _verify_release_commands()
    except (KeyError, OSError, ValueError, json.JSONDecodeError, tomllib.TOMLDecodeError) as exc:
        print(f"dependency-lock verification failed: {exc}", file=sys.stderr)
        return 1
    print("dependency locks and release install commands verified")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
